// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, updated_at, changed_by, changed_by_api_key, action, table_name, object_id, before_value, updated_values FROM "AuditLog"
WHERE id = $1
`

func (q *Queries) GetAuditLog(ctx context.Context, id string) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.ChangedBy,
		&i.ChangedByApiKey,
		&i.Action,
		&i.TableName,
		&i.ObjectID,
		&i.BeforeValue,
		&i.UpdatedValues,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO "AuditLog" (
    changed_by, changed_by_api_key, action, table_name, object_id,
    before_value, updated_values
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, updated_at, changed_by, changed_by_api_key, action, table_name, object_id, before_value, updated_values
`

type InsertAuditLogParams struct {
	ChangedBy       string `json:"changed_by"`
	ChangedByApiKey string `json:"changed_by_api_key"`
	Action          string `json:"action"`
	TableName       string `json:"table_name"`
	ObjectID        string `json:"object_id"`
	BeforeValue     []byte `json:"before_value"`
	UpdatedValues   []byte `json:"updated_values"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ChangedBy,
		arg.ChangedByApiKey,
		arg.Action,
		arg.TableName,
		arg.ObjectID,
		arg.BeforeValue,
		arg.UpdatedValues,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.ChangedBy,
		&i.ChangedByApiKey,
		&i.Action,
		&i.TableName,
		&i.ObjectID,
		&i.BeforeValue,
		&i.UpdatedValues,
	)
	return i, err
}

const insertDeletedTeam = `-- name: InsertDeletedTeam :exec
INSERT INTO "DeletedTeamTable" (
    team_id, team_alias, organization_id, admins, members,
    members_with_roles, metadata, max_budget, spend, models,
    blocked, tpm_limit, rpm_limit, budget_duration, budget_reset_at,
    budget_id, created_at, created_by, updated_at, updated_by,
    deleted_by, deleted_by_api_key, tianji_changed_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23
)
`

type InsertDeletedTeamParams struct {
	TeamID           string             `json:"team_id"`
	TeamAlias        *string            `json:"team_alias"`
	OrganizationID   *string            `json:"organization_id"`
	Admins           []string           `json:"admins"`
	Members          []string           `json:"members"`
	MembersWithRoles []byte             `json:"members_with_roles"`
	Metadata         []byte             `json:"metadata"`
	MaxBudget        *float64           `json:"max_budget"`
	Spend            float64            `json:"spend"`
	Models           []string           `json:"models"`
	Blocked          bool               `json:"blocked"`
	TpmLimit         *int64             `json:"tpm_limit"`
	RpmLimit         *int64             `json:"rpm_limit"`
	BudgetDuration   *string            `json:"budget_duration"`
	BudgetResetAt    pgtype.Timestamptz `json:"budget_reset_at"`
	BudgetID         *string            `json:"budget_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        string             `json:"created_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy        string             `json:"updated_by"`
	DeletedBy        string             `json:"deleted_by"`
	DeletedByApiKey  string             `json:"deleted_by_api_key"`
	TianjiChangedBy  string             `json:"tianji_changed_by"`
}

func (q *Queries) InsertDeletedTeam(ctx context.Context, arg InsertDeletedTeamParams) error {
	_, err := q.db.Exec(ctx, insertDeletedTeam,
		arg.TeamID,
		arg.TeamAlias,
		arg.OrganizationID,
		arg.Admins,
		arg.Members,
		arg.MembersWithRoles,
		arg.Metadata,
		arg.MaxBudget,
		arg.Spend,
		arg.Models,
		arg.Blocked,
		arg.TpmLimit,
		arg.RpmLimit,
		arg.BudgetDuration,
		arg.BudgetResetAt,
		arg.BudgetID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedBy,
		arg.DeletedByApiKey,
		arg.TianjiChangedBy,
	)
	return err
}

const insertDeletedVerificationToken = `-- name: InsertDeletedVerificationToken :exec
INSERT INTO "DeletedVerificationToken" (
    token, key_name, key_alias, spend, max_budget, expires,
    models, aliases, config, user_id, team_id, organization_id,
    permissions, metadata, blocked, tpm_limit, rpm_limit,
    budget_duration, budget_reset_at, allowed_cache_controls, allowed_routes,
    policies, access_group_ids, model_spend, model_max_budget,
    soft_budget_cooldown, budget_id, object_permission_id,
    created_at, created_by, updated_at, updated_by,
    deleted_by, deleted_by_api_key, tianji_changed_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20, $21,
    $22, $23, $24, $25,
    $26, $27, $28,
    $29, $30, $31, $32,
    $33, $34, $35
)
`

type InsertDeletedVerificationTokenParams struct {
	Token                string             `json:"token"`
	KeyName              *string            `json:"key_name"`
	KeyAlias             *string            `json:"key_alias"`
	Spend                float64            `json:"spend"`
	MaxBudget            *float64           `json:"max_budget"`
	Expires              pgtype.Timestamptz `json:"expires"`
	Models               []string           `json:"models"`
	Aliases              []byte             `json:"aliases"`
	Config               []byte             `json:"config"`
	UserID               *string            `json:"user_id"`
	TeamID               *string            `json:"team_id"`
	OrganizationID       *string            `json:"organization_id"`
	Permissions          []byte             `json:"permissions"`
	Metadata             []byte             `json:"metadata"`
	Blocked              *bool              `json:"blocked"`
	TpmLimit             *int64             `json:"tpm_limit"`
	RpmLimit             *int64             `json:"rpm_limit"`
	BudgetDuration       *string            `json:"budget_duration"`
	BudgetResetAt        pgtype.Timestamptz `json:"budget_reset_at"`
	AllowedCacheControls []string           `json:"allowed_cache_controls"`
	AllowedRoutes        []string           `json:"allowed_routes"`
	Policies             []string           `json:"policies"`
	AccessGroupIds       []string           `json:"access_group_ids"`
	ModelSpend           []byte             `json:"model_spend"`
	ModelMaxBudget       []byte             `json:"model_max_budget"`
	SoftBudgetCooldown   bool               `json:"soft_budget_cooldown"`
	BudgetID             *string            `json:"budget_id"`
	ObjectPermissionID   *string            `json:"object_permission_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedBy            *string            `json:"created_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy            *string            `json:"updated_by"`
	DeletedBy            string             `json:"deleted_by"`
	DeletedByApiKey      string             `json:"deleted_by_api_key"`
	TianjiChangedBy      string             `json:"tianji_changed_by"`
}

func (q *Queries) InsertDeletedVerificationToken(ctx context.Context, arg InsertDeletedVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertDeletedVerificationToken,
		arg.Token,
		arg.KeyName,
		arg.KeyAlias,
		arg.Spend,
		arg.MaxBudget,
		arg.Expires,
		arg.Models,
		arg.Aliases,
		arg.Config,
		arg.UserID,
		arg.TeamID,
		arg.OrganizationID,
		arg.Permissions,
		arg.Metadata,
		arg.Blocked,
		arg.TpmLimit,
		arg.RpmLimit,
		arg.BudgetDuration,
		arg.BudgetResetAt,
		arg.AllowedCacheControls,
		arg.AllowedRoutes,
		arg.Policies,
		arg.AccessGroupIds,
		arg.ModelSpend,
		arg.ModelMaxBudget,
		arg.SoftBudgetCooldown,
		arg.BudgetID,
		arg.ObjectPermissionID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedBy,
		arg.DeletedByApiKey,
		arg.TianjiChangedBy,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, updated_at, changed_by, changed_by_api_key, action, table_name, object_id, before_value, updated_values FROM "AuditLog"
WHERE
    ($1::text = '' OR changed_by = $1) AND
    ($2::text = '' OR action = $2) AND
    ($3::text = '' OR table_name = $3) AND
    ($4::text = '' OR object_id = $4) AND
    ($5::timestamptz IS NULL OR updated_at >= $5) AND
    ($6::timestamptz IS NULL OR updated_at <= $6)
ORDER BY updated_at DESC
LIMIT $7 OFFSET $8
`

type ListAuditLogsParams struct {
	Column1 string             `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 string             `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Column6 pgtype.Timestamptz `json:"column_6"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UpdatedAt,
			&i.ChangedBy,
			&i.ChangedByApiKey,
			&i.Action,
			&i.TableName,
			&i.ObjectID,
			&i.BeforeValue,
			&i.UpdatedValues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
