// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential.sql

package db

import (
	"context"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO "CredentialTable" (credential_id, credential_name, credential_type, credential_value, credential_info, organization_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING credential_id, credential_name, credential_type, credential_value, credential_info, organization_id, created_at, created_by, updated_at, updated_by
`

type CreateCredentialParams struct {
	CredentialID    string  `json:"credential_id"`
	CredentialName  string  `json:"credential_name"`
	CredentialType  string  `json:"credential_type"`
	CredentialValue string  `json:"credential_value"`
	CredentialInfo  []byte  `json:"credential_info"`
	OrganizationID  *string `json:"organization_id"`
	CreatedBy       string  `json:"created_by"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (CredentialTable, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.CredentialID,
		arg.CredentialName,
		arg.CredentialType,
		arg.CredentialValue,
		arg.CredentialInfo,
		arg.OrganizationID,
		arg.CreatedBy,
	)
	var i CredentialTable
	err := row.Scan(
		&i.CredentialID,
		&i.CredentialName,
		&i.CredentialType,
		&i.CredentialValue,
		&i.CredentialInfo,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM "CredentialTable" WHERE credential_id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, credentialID string) error {
	_, err := q.db.Exec(ctx, deleteCredential, credentialID)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT credential_id, credential_name, credential_type, credential_value, credential_info, organization_id, created_at, created_by, updated_at, updated_by FROM "CredentialTable" WHERE credential_id = $1
`

func (q *Queries) GetCredential(ctx context.Context, credentialID string) (CredentialTable, error) {
	row := q.db.QueryRow(ctx, getCredential, credentialID)
	var i CredentialTable
	err := row.Scan(
		&i.CredentialID,
		&i.CredentialName,
		&i.CredentialType,
		&i.CredentialValue,
		&i.CredentialInfo,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT credential_id, credential_name, credential_type, credential_value, credential_info, organization_id, created_at, created_by, updated_at, updated_by FROM "CredentialTable" ORDER BY created_at DESC
`

func (q *Queries) ListCredentials(ctx context.Context) ([]CredentialTable, error) {
	rows, err := q.db.Query(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialTable
	for rows.Next() {
		var i CredentialTable
		if err := rows.Scan(
			&i.CredentialID,
			&i.CredentialName,
			&i.CredentialType,
			&i.CredentialValue,
			&i.CredentialInfo,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByOrg = `-- name: ListCredentialsByOrg :many
SELECT credential_id, credential_name, credential_type, credential_value, credential_info, organization_id, created_at, created_by, updated_at, updated_by FROM "CredentialTable" WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCredentialsByOrg(ctx context.Context, organizationID *string) ([]CredentialTable, error) {
	rows, err := q.db.Query(ctx, listCredentialsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialTable
	for rows.Next() {
		var i CredentialTable
		if err := rows.Scan(
			&i.CredentialID,
			&i.CredentialName,
			&i.CredentialType,
			&i.CredentialValue,
			&i.CredentialInfo,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE "CredentialTable"
SET credential_value = $2, updated_at = NOW()
WHERE credential_id = $1
`

type UpdateCredentialParams struct {
	CredentialID    string `json:"credential_id"`
	CredentialValue string `json:"credential_value"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential, arg.CredentialID, arg.CredentialValue)
	return err
}
