// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: error_log.sql

package db

import (
	"context"
)

const insertErrorLog = `-- name: InsertErrorLog :exec
INSERT INTO "ErrorLogs" (
    request_id, api_key_hash, model, provider,
    status_code, error_type, error_message, traceback, team_id,
    upstream_token_key, end_user, organization_id, reasoning_effort
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertErrorLogParams struct {
	RequestID        string  `json:"request_id"`
	ApiKeyHash       string  `json:"api_key_hash"`
	Model            string  `json:"model"`
	Provider         string  `json:"provider"`
	StatusCode       int32   `json:"status_code"`
	ErrorType        string  `json:"error_type"`
	ErrorMessage     string  `json:"error_message"`
	Traceback        string  `json:"traceback"`
	TeamID           *string `json:"team_id"`
	UpstreamTokenKey string  `json:"upstream_token_key"`
	EndUser          string  `json:"end_user"`
	OrganizationID   string  `json:"organization_id"`
	ReasoningEffort  string  `json:"reasoning_effort"`
}

func (q *Queries) InsertErrorLog(ctx context.Context, arg InsertErrorLogParams) error {
	_, err := q.db.Exec(ctx, insertErrorLog,
		arg.RequestID,
		arg.ApiKeyHash,
		arg.Model,
		arg.Provider,
		arg.StatusCode,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.Traceback,
		arg.TeamID,
		arg.UpstreamTokenKey,
		arg.EndUser,
		arg.OrganizationID,
		arg.ReasoningEffort,
	)
	return err
}

const listErrorLogs = `-- name: ListErrorLogs :many
SELECT
    id,
    request_id,
    api_key_hash,
    model,
    provider,
    status_code,
    error_type,
    error_message,
    traceback,
    created_at,
    team_id,
    upstream_token_key,
    end_user,
    organization_id,
    reasoning_effort
FROM "ErrorLogs"
WHERE ($1::text IS NULL OR model = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListErrorLogsParams struct {
	FilterModel *string `json:"filter_model"`
	QueryOffset int32   `json:"query_offset"`
	QueryLimit  int32   `json:"query_limit"`
}

func (q *Queries) ListErrorLogs(ctx context.Context, arg ListErrorLogsParams) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listErrorLogs, arg.FilterModel, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErrorLog
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ApiKeyHash,
			&i.Model,
			&i.Provider,
			&i.StatusCode,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.Traceback,
			&i.CreatedAt,
			&i.TeamID,
			&i.UpstreamTokenKey,
			&i.EndUser,
			&i.OrganizationID,
			&i.ReasoningEffort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
