// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guardrail_mgmt.sql

package db

import (
	"context"
)

const createGuardrailConfig = `-- name: CreateGuardrailConfig :one
INSERT INTO "GuardrailConfigTable" (guardrail_name, guardrail_type, config, failure_policy, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, guardrail_name, guardrail_type, config, failure_policy, enabled, created_at, updated_at
`

type CreateGuardrailConfigParams struct {
	GuardrailName string `json:"guardrail_name"`
	GuardrailType string `json:"guardrail_type"`
	Config        []byte `json:"config"`
	FailurePolicy string `json:"failure_policy"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) CreateGuardrailConfig(ctx context.Context, arg CreateGuardrailConfigParams) (GuardrailConfigTable, error) {
	row := q.db.QueryRow(ctx, createGuardrailConfig,
		arg.GuardrailName,
		arg.GuardrailType,
		arg.Config,
		arg.FailurePolicy,
		arg.Enabled,
	)
	var i GuardrailConfigTable
	err := row.Scan(
		&i.ID,
		&i.GuardrailName,
		&i.GuardrailType,
		&i.Config,
		&i.FailurePolicy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGuardrailConfig = `-- name: DeleteGuardrailConfig :exec
DELETE FROM "GuardrailConfigTable" WHERE id = $1
`

func (q *Queries) DeleteGuardrailConfig(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGuardrailConfig, id)
	return err
}

const getGuardrailConfig = `-- name: GetGuardrailConfig :one
SELECT id, guardrail_name, guardrail_type, config, failure_policy, enabled, created_at, updated_at FROM "GuardrailConfigTable" WHERE id = $1
`

func (q *Queries) GetGuardrailConfig(ctx context.Context, id string) (GuardrailConfigTable, error) {
	row := q.db.QueryRow(ctx, getGuardrailConfig, id)
	var i GuardrailConfigTable
	err := row.Scan(
		&i.ID,
		&i.GuardrailName,
		&i.GuardrailType,
		&i.Config,
		&i.FailurePolicy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuardrailConfigByName = `-- name: GetGuardrailConfigByName :one
SELECT id, guardrail_name, guardrail_type, config, failure_policy, enabled, created_at, updated_at FROM "GuardrailConfigTable" WHERE guardrail_name = $1
`

func (q *Queries) GetGuardrailConfigByName(ctx context.Context, guardrailName string) (GuardrailConfigTable, error) {
	row := q.db.QueryRow(ctx, getGuardrailConfigByName, guardrailName)
	var i GuardrailConfigTable
	err := row.Scan(
		&i.ID,
		&i.GuardrailName,
		&i.GuardrailType,
		&i.Config,
		&i.FailurePolicy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuardrailConfigs = `-- name: ListGuardrailConfigs :many
SELECT id, guardrail_name, guardrail_type, config, failure_policy, enabled, created_at, updated_at FROM "GuardrailConfigTable" ORDER BY guardrail_name ASC
`

func (q *Queries) ListGuardrailConfigs(ctx context.Context) ([]GuardrailConfigTable, error) {
	rows, err := q.db.Query(ctx, listGuardrailConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuardrailConfigTable
	for rows.Next() {
		var i GuardrailConfigTable
		if err := rows.Scan(
			&i.ID,
			&i.GuardrailName,
			&i.GuardrailType,
			&i.Config,
			&i.FailurePolicy,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuardrailConfig = `-- name: UpdateGuardrailConfig :one
UPDATE "GuardrailConfigTable"
SET guardrail_name = COALESCE($2, guardrail_name),
    guardrail_type = COALESCE($3, guardrail_type),
    config = COALESCE($4, config),
    failure_policy = COALESCE($5, failure_policy),
    enabled = COALESCE($6, enabled),
    updated_at = NOW()
WHERE id = $1
RETURNING id, guardrail_name, guardrail_type, config, failure_policy, enabled, created_at, updated_at
`

type UpdateGuardrailConfigParams struct {
	ID            string `json:"id"`
	GuardrailName string `json:"guardrail_name"`
	GuardrailType string `json:"guardrail_type"`
	Config        []byte `json:"config"`
	FailurePolicy string `json:"failure_policy"`
	Enabled       bool   `json:"enabled"`
}

func (q *Queries) UpdateGuardrailConfig(ctx context.Context, arg UpdateGuardrailConfigParams) (GuardrailConfigTable, error) {
	row := q.db.QueryRow(ctx, updateGuardrailConfig,
		arg.ID,
		arg.GuardrailName,
		arg.GuardrailType,
		arg.Config,
		arg.FailurePolicy,
		arg.Enabled,
	)
	var i GuardrailConfigTable
	err := row.Scan(
		&i.ID,
		&i.GuardrailName,
		&i.GuardrailType,
		&i.Config,
		&i.FailurePolicy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
