// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health_check.sql

package db

import (
	"context"
)

const insertHealthCheck = `-- name: InsertHealthCheck :exec
INSERT INTO "HealthCheckTable" (model_name, status, response_time_ms, error_message)
VALUES ($1, $2, $3, $4)
`

type InsertHealthCheckParams struct {
	ModelName      string  `json:"model_name"`
	Status         string  `json:"status"`
	ResponseTimeMs float64 `json:"response_time_ms"`
	ErrorMessage   string  `json:"error_message"`
}

func (q *Queries) InsertHealthCheck(ctx context.Context, arg InsertHealthCheckParams) error {
	_, err := q.db.Exec(ctx, insertHealthCheck,
		arg.ModelName,
		arg.Status,
		arg.ResponseTimeMs,
		arg.ErrorMessage,
	)
	return err
}

const listHealthChecks = `-- name: ListHealthChecks :many
SELECT id, model_name, status, response_time_ms, error_message, checked_at FROM "HealthCheckTable"
WHERE ($1::text = '' OR model_name = $1)
ORDER BY checked_at DESC
LIMIT $2 OFFSET $3
`

type ListHealthChecksParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListHealthChecks(ctx context.Context, arg ListHealthChecksParams) ([]HealthCheckTable, error) {
	rows, err := q.db.Query(ctx, listHealthChecks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthCheckTable
	for rows.Next() {
		var i HealthCheckTable
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.Status,
			&i.ResponseTimeMs,
			&i.ErrorMessage,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
