// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentsTable struct {
	AgentID           string             `json:"agent_id"`
	AgentName         string             `json:"agent_name"`
	TianjiParams      []byte             `json:"tianji_params"`
	AgentCardParams   []byte             `json:"agent_card_params"`
	AgentAccessGroups []string           `json:"agent_access_groups"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         string             `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         string             `json:"updated_by"`
}

type AuditLog struct {
	ID              string             `json:"id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ChangedBy       string             `json:"changed_by"`
	ChangedByApiKey string             `json:"changed_by_api_key"`
	Action          string             `json:"action"`
	TableName       string             `json:"table_name"`
	ObjectID        string             `json:"object_id"`
	BeforeValue     []byte             `json:"before_value"`
	UpdatedValues   []byte             `json:"updated_values"`
}

type BudgetTable struct {
	BudgetID            string             `json:"budget_id"`
	MaxBudget           *float64           `json:"max_budget"`
	SoftBudget          *float64           `json:"soft_budget"`
	MaxParallelRequests *int32             `json:"max_parallel_requests"`
	TpmLimit            *int64             `json:"tpm_limit"`
	RpmLimit            *int64             `json:"rpm_limit"`
	ModelMaxBudget      []byte             `json:"model_max_budget"`
	BudgetDuration      *string            `json:"budget_duration"`
	BudgetResetAt       pgtype.Timestamptz `json:"budget_reset_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CreatedBy           string             `json:"created_by"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy           string             `json:"updated_by"`
}

type ClaudeCodePluginTable struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Version      string             `json:"version"`
	Description  string             `json:"description"`
	ManifestJson []byte             `json:"manifest_json"`
	FilesJson    []byte             `json:"files_json"`
	Enabled      bool               `json:"enabled"`
	Source       string             `json:"source"`
	SourceUrl    string             `json:"source_url"`
	CreatedBy    string             `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CredentialTable struct {
	CredentialID    string             `json:"credential_id"`
	CredentialName  string             `json:"credential_name"`
	CredentialType  string             `json:"credential_type"`
	CredentialValue string             `json:"credential_value"`
	CredentialInfo  []byte             `json:"credential_info"`
	OrganizationID  *string            `json:"organization_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedBy       string             `json:"created_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy       string             `json:"updated_by"`
}

type DailyAgentSpend struct {
	ID                       string             `json:"id"`
	AgentID                  string             `json:"agent_id"`
	Date                     pgtype.Date        `json:"date"`
	ApiKey                   string             `json:"api_key"`
	Model                    string             `json:"model"`
	ModelGroup               string             `json:"model_group"`
	CustomLlmProvider        string             `json:"custom_llm_provider"`
	McpNamespacedToolName    string             `json:"mcp_namespaced_tool_name"`
	Endpoint                 string             `json:"endpoint"`
	PromptTokens             int64              `json:"prompt_tokens"`
	CompletionTokens         int64              `json:"completion_tokens"`
	CacheReadInputTokens     int64              `json:"cache_read_input_tokens"`
	CacheCreationInputTokens int64              `json:"cache_creation_input_tokens"`
	Spend                    float64            `json:"spend"`
	ApiRequests              int64              `json:"api_requests"`
	SuccessfulRequests       int64              `json:"successful_requests"`
	FailedRequests           int64              `json:"failed_requests"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type DailyEndUserSpend struct {
	ID               string             `json:"id"`
	EndUserID        string             `json:"end_user_id"`
	Date             pgtype.Date        `json:"date"`
	Model            string             `json:"model"`
	ApiKey           string             `json:"api_key"`
	Spend            float64            `json:"spend"`
	PromptTokens     int64              `json:"prompt_tokens"`
	CompletionTokens int64              `json:"completion_tokens"`
	ApiRequests      int64              `json:"api_requests"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DailyOrganizationSpend struct {
	ID               string             `json:"id"`
	OrganizationID   string             `json:"organization_id"`
	Date             pgtype.Date        `json:"date"`
	Model            string             `json:"model"`
	Spend            float64            `json:"spend"`
	PromptTokens     int64              `json:"prompt_tokens"`
	CompletionTokens int64              `json:"completion_tokens"`
	ApiRequests      int64              `json:"api_requests"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DeletedTeamTable struct {
	TeamID           string             `json:"team_id"`
	TeamAlias        *string            `json:"team_alias"`
	OrganizationID   *string            `json:"organization_id"`
	Admins           []string           `json:"admins"`
	Members          []string           `json:"members"`
	MembersWithRoles []byte             `json:"members_with_roles"`
	Metadata         []byte             `json:"metadata"`
	MaxBudget        *float64           `json:"max_budget"`
	Spend            float64            `json:"spend"`
	Models           []string           `json:"models"`
	Blocked          bool               `json:"blocked"`
	TpmLimit         *int64             `json:"tpm_limit"`
	RpmLimit         *int64             `json:"rpm_limit"`
	BudgetDuration   *string            `json:"budget_duration"`
	BudgetResetAt    pgtype.Timestamptz `json:"budget_reset_at"`
	BudgetID         *string            `json:"budget_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        string             `json:"created_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy        string             `json:"updated_by"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy        string             `json:"deleted_by"`
	DeletedByApiKey  string             `json:"deleted_by_api_key"`
	TianjiChangedBy  string             `json:"tianji_changed_by"`
}

type DeletedVerificationToken struct {
	Token                string             `json:"token"`
	KeyName              *string            `json:"key_name"`
	KeyAlias             *string            `json:"key_alias"`
	Spend                float64            `json:"spend"`
	MaxBudget            *float64           `json:"max_budget"`
	Expires              pgtype.Timestamptz `json:"expires"`
	Models               []string           `json:"models"`
	Aliases              []byte             `json:"aliases"`
	Config               []byte             `json:"config"`
	UserID               *string            `json:"user_id"`
	TeamID               *string            `json:"team_id"`
	OrganizationID       *string            `json:"organization_id"`
	Permissions          []byte             `json:"permissions"`
	Metadata             []byte             `json:"metadata"`
	Blocked              *bool              `json:"blocked"`
	TpmLimit             *int64             `json:"tpm_limit"`
	RpmLimit             *int64             `json:"rpm_limit"`
	BudgetDuration       *string            `json:"budget_duration"`
	BudgetResetAt        pgtype.Timestamptz `json:"budget_reset_at"`
	AllowedCacheControls []string           `json:"allowed_cache_controls"`
	AllowedRoutes        []string           `json:"allowed_routes"`
	Policies             []string           `json:"policies"`
	AccessGroupIds       []string           `json:"access_group_ids"`
	ModelSpend           []byte             `json:"model_spend"`
	ModelMaxBudget       []byte             `json:"model_max_budget"`
	SoftBudgetCooldown   bool               `json:"soft_budget_cooldown"`
	BudgetID             *string            `json:"budget_id"`
	ObjectPermissionID   *string            `json:"object_permission_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedBy            *string            `json:"created_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy            *string            `json:"updated_by"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy            string             `json:"deleted_by"`
	DeletedByApiKey      string             `json:"deleted_by_api_key"`
	TianjiChangedBy      string             `json:"tianji_changed_by"`
}

type EndUserTable struct {
	UserID             string             `json:"user_id"`
	Alias              *string            `json:"alias"`
	Spend              float64            `json:"spend"`
	AllowedModelRegion *string            `json:"allowed_model_region"`
	DefaultModel       *string            `json:"default_model"`
	TianjiBudgetTable  *string            `json:"tianji_budget_table"`
	Blocked            bool               `json:"blocked"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type EndUserTable2 struct {
	ID                 string             `json:"id"`
	EndUserID          string             `json:"end_user_id"`
	Alias              *string            `json:"alias"`
	AllowedModelRegion *string            `json:"allowed_model_region"`
	DefaultModel       *string            `json:"default_model"`
	Budget             *float64           `json:"budget"`
	Blocked            bool               `json:"blocked"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ErrorLog struct {
	ID           string             `json:"id"`
	RequestID    string             `json:"request_id"`
	ApiKeyHash   string             `json:"api_key_hash"`
	Model        string             `json:"model"`
	Provider     string             `json:"provider"`
	StatusCode   int32              `json:"status_code"`
	ErrorType    string             `json:"error_type"`
	ErrorMessage string             `json:"error_message"`
	Traceback    string             `json:"traceback"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type GuardrailConfigTable struct {
	ID            string             `json:"id"`
	GuardrailName string             `json:"guardrail_name"`
	GuardrailType string             `json:"guardrail_type"`
	Config        []byte             `json:"config"`
	FailurePolicy string             `json:"failure_policy"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type HealthCheckTable struct {
	ID             string             `json:"id"`
	ModelName      string             `json:"model_name"`
	Status         string             `json:"status"`
	ResponseTimeMs float64            `json:"response_time_ms"`
	ErrorMessage   string             `json:"error_message"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

type IPWhitelistTable struct {
	ID          string             `json:"id"`
	IpAddress   string             `json:"ip_address"`
	Description *string            `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MCPServerTable struct {
	ID              string             `json:"id"`
	ServerID        string             `json:"server_id"`
	Alias           string             `json:"alias"`
	Transport       string             `json:"transport"`
	Url             string             `json:"url"`
	Command         string             `json:"command"`
	Args            []string           `json:"args"`
	AuthType        string             `json:"auth_type"`
	AuthToken       string             `json:"auth_token"`
	StaticHeaders   []byte             `json:"static_headers"`
	AllowedTools    []string           `json:"allowed_tools"`
	DisallowedTools []string           `json:"disallowed_tools"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ModelAccessGroup struct {
	GroupID        string             `json:"group_id"`
	GroupAlias     *string            `json:"group_alias"`
	Models         []string           `json:"models"`
	OrganizationID *string            `json:"organization_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      string             `json:"created_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      string             `json:"updated_by"`
}

type ModelPricing struct {
	ModelName          string             `json:"model_name"`
	InputCostPerToken  float64            `json:"input_cost_per_token"`
	OutputCostPerToken float64            `json:"output_cost_per_token"`
	MaxInputTokens     int32              `json:"max_input_tokens"`
	MaxOutputTokens    int32              `json:"max_output_tokens"`
	MaxTokens          int32              `json:"max_tokens"`
	Mode               string             `json:"mode"`
	Provider           string             `json:"provider"`
	SourceUrl          string             `json:"source_url"`
	SyncedAt           pgtype.Timestamptz `json:"synced_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembership struct {
	UserID         string             `json:"user_id"`
	OrganizationID string             `json:"organization_id"`
	UserRole       *string            `json:"user_role"`
	Spend          float64            `json:"spend"`
	BudgetID       *string            `json:"budget_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationTable struct {
	OrganizationID    string             `json:"organization_id"`
	OrganizationAlias *string            `json:"organization_alias"`
	BudgetID          *string            `json:"budget_id"`
	Metadata          []byte             `json:"metadata"`
	Models            []string           `json:"models"`
	Spend             float64            `json:"spend"`
	MaxBudget         *float64           `json:"max_budget"`
	TpmLimit          *int64             `json:"tpm_limit"`
	RpmLimit          *int64             `json:"rpm_limit"`
	BudgetDuration    *string            `json:"budget_duration"`
	BudgetResetAt     pgtype.Timestamptz `json:"budget_reset_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         string             `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         string             `json:"updated_by"`
}

type PolicyAttachmentTable struct {
	ID         string             `json:"id"`
	PolicyName string             `json:"policy_name"`
	Scope      *string            `json:"scope"`
	Teams      []string           `json:"teams"`
	Keys       []string           `json:"keys"`
	Models     []string           `json:"models"`
	Tags       []string           `json:"tags"`
	CreatedBy  *string            `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PolicyTable struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	ParentID         *string            `json:"parent_id"`
	Conditions       []byte             `json:"conditions"`
	GuardrailsAdd    []string           `json:"guardrails_add"`
	GuardrailsRemove []string           `json:"guardrails_remove"`
	Pipeline         []byte             `json:"pipeline"`
	Description      *string            `json:"description"`
	CreatedBy        *string            `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PromptTemplateTable struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Version   int32              `json:"version"`
	Template  string             `json:"template"`
	Variables []string           `json:"variables"`
	Model     *string            `json:"model"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProxyModelTable struct {
	ModelID      string             `json:"model_id"`
	ModelName    string             `json:"model_name"`
	TianjiParams []byte             `json:"tianji_params"`
	ModelInfo    []byte             `json:"model_info"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    string             `json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    string             `json:"updated_by"`
}

type SkillsTable struct {
	SkillID       string             `json:"skill_id"`
	DisplayTitle  string             `json:"display_title"`
	Description   string             `json:"description"`
	Instructions  string             `json:"instructions"`
	Source        string             `json:"source"`
	LatestVersion string             `json:"latest_version"`
	FileContent   []byte             `json:"file_content"`
	FileName      string             `json:"file_name"`
	FileType      string             `json:"file_type"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     string             `json:"created_by"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy     string             `json:"updated_by"`
}

type SpendArchiveTable struct {
	ID              string             `json:"id"`
	DateFrom        pgtype.Date        `json:"date_from"`
	DateTo          pgtype.Date        `json:"date_to"`
	StorageType     string             `json:"storage_type"`
	StorageLocation string             `json:"storage_location"`
	EntryCount      int64              `json:"entry_count"`
	ExportedAt      pgtype.Timestamptz `json:"exported_at"`
}

type SpendLog struct {
	RequestID          string             `json:"request_id"`
	CallType           string             `json:"call_type"`
	ApiKey             string             `json:"api_key"`
	Spend              float64            `json:"spend"`
	TotalTokens        int32              `json:"total_tokens"`
	PromptTokens       int32              `json:"prompt_tokens"`
	CompletionTokens   int32              `json:"completion_tokens"`
	Starttime          pgtype.Timestamptz `json:"starttime"`
	Endtime            pgtype.Timestamptz `json:"endtime"`
	Completionstartime pgtype.Timestamptz `json:"completionstartime"`
	Model              string             `json:"model"`
	ModelID            string             `json:"model_id"`
	ModelGroup         string             `json:"model_group"`
	ApiBase            string             `json:"api_base"`
	User               string             `json:"user"`
	Metadata           []byte             `json:"metadata"`
	CacheHit           string             `json:"cache_hit"`
	CacheKey           string             `json:"cache_key"`
	RequestTags        []string           `json:"request_tags"`
	TeamID             *string            `json:"team_id"`
	EndUser            *string            `json:"end_user"`
	RequesterIpAddress *string            `json:"requester_ip_address"`
	OrganizationID     *string            `json:"organization_id"`
	Provider           string             `json:"provider"`
}

type TagTable struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TeamTable struct {
	TeamID           string             `json:"team_id"`
	TeamAlias        *string            `json:"team_alias"`
	OrganizationID   *string            `json:"organization_id"`
	Admins           []string           `json:"admins"`
	Members          []string           `json:"members"`
	MembersWithRoles []byte             `json:"members_with_roles"`
	Metadata         []byte             `json:"metadata"`
	MaxBudget        *float64           `json:"max_budget"`
	Spend            float64            `json:"spend"`
	Models           []string           `json:"models"`
	Blocked          bool               `json:"blocked"`
	TpmLimit         *int64             `json:"tpm_limit"`
	RpmLimit         *int64             `json:"rpm_limit"`
	BudgetDuration   *string            `json:"budget_duration"`
	BudgetResetAt    pgtype.Timestamptz `json:"budget_reset_at"`
	BudgetID         *string            `json:"budget_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        string             `json:"created_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy        string             `json:"updated_by"`
}

type UserTable struct {
	UserID         string             `json:"user_id"`
	UserAlias      *string            `json:"user_alias"`
	UserEmail      *string            `json:"user_email"`
	UserRole       string             `json:"user_role"`
	Teams          []string           `json:"teams"`
	MaxBudget      *float64           `json:"max_budget"`
	Spend          float64            `json:"spend"`
	Models         []string           `json:"models"`
	Metadata       []byte             `json:"metadata"`
	TpmLimit       *int64             `json:"tpm_limit"`
	RpmLimit       *int64             `json:"rpm_limit"`
	BudgetDuration *string            `json:"budget_duration"`
	BudgetResetAt  pgtype.Timestamptz `json:"budget_reset_at"`
	BudgetID       *string            `json:"budget_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedBy      string             `json:"created_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      string             `json:"updated_by"`
}

type VerificationToken struct {
	Token                string             `json:"token"`
	KeyName              *string            `json:"key_name"`
	KeyAlias             *string            `json:"key_alias"`
	Spend                float64            `json:"spend"`
	MaxBudget            *float64           `json:"max_budget"`
	Expires              pgtype.Timestamptz `json:"expires"`
	Models               []string           `json:"models"`
	Aliases              []byte             `json:"aliases"`
	Config               []byte             `json:"config"`
	UserID               *string            `json:"user_id"`
	TeamID               *string            `json:"team_id"`
	OrganizationID       *string            `json:"organization_id"`
	Permissions          []byte             `json:"permissions"`
	Metadata             []byte             `json:"metadata"`
	Blocked              *bool              `json:"blocked"`
	TpmLimit             *int64             `json:"tpm_limit"`
	RpmLimit             *int64             `json:"rpm_limit"`
	BudgetDuration       *string            `json:"budget_duration"`
	BudgetResetAt        pgtype.Timestamptz `json:"budget_reset_at"`
	AllowedCacheControls []string           `json:"allowed_cache_controls"`
	AllowedRoutes        []string           `json:"allowed_routes"`
	Policies             []string           `json:"policies"`
	AccessGroupIds       []string           `json:"access_group_ids"`
	ModelSpend           []byte             `json:"model_spend"`
	ModelMaxBudget       []byte             `json:"model_max_budget"`
	SoftBudgetCooldown   bool               `json:"soft_budget_cooldown"`
	BudgetID             *string            `json:"budget_id"`
	ObjectPermissionID   *string            `json:"object_permission_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedBy            *string            `json:"created_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy            *string            `json:"updated_by"`
}
