// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_token_ratelimit_state.sql

package db

import (
	"context"
)

const getActiveOAuthTokenRateLimitStates = `-- name: GetActiveOAuthTokenRateLimitStates :many
SELECT token_key, unified_status,
    unified_5h_status, unified_5h_utilization, unified_5h_reset,
    unified_7d_status, unified_7d_utilization, unified_7d_reset,
    unified_7d_sonnet_status, unified_7d_sonnet_utilization, unified_7d_sonnet_reset,
    org_id, updated_at, unified_reset
FROM "OAuthTokenRateLimitState"
WHERE unified_7d_reset ~ '^\d+$' AND unified_7d_reset::bigint > extract(epoch from now())::bigint
`

// Returns tokens whose 7d window has not yet reset (utilization data is still valid).
// Used by PreloadRateLimitStore at startup. Tokens with expired 7d windows are omitted
// because Anthropic has already zeroed their counters — the default (1, 0) score is correct.
func (q *Queries) GetActiveOAuthTokenRateLimitStates(ctx context.Context) ([]OAuthTokenRateLimitState, error) {
	rows, err := q.db.Query(ctx, getActiveOAuthTokenRateLimitStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OAuthTokenRateLimitState
	for rows.Next() {
		var i OAuthTokenRateLimitState
		if err := rows.Scan(
			&i.TokenKey,
			&i.UnifiedStatus,
			&i.Unified5hStatus,
			&i.Unified5hUtilization,
			&i.Unified5hReset,
			&i.Unified7dStatus,
			&i.Unified7dUtilization,
			&i.Unified7dReset,
			&i.Unified7dSonnetStatus,
			&i.Unified7dSonnetUtilization,
			&i.Unified7dSonnetReset,
			&i.OrgID,
			&i.UpdatedAt,
			&i.UnifiedReset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthTokenRateLimitState = `-- name: GetOAuthTokenRateLimitState :one
SELECT token_key, unified_status,
    unified_5h_status, unified_5h_utilization, unified_5h_reset,
    unified_7d_status, unified_7d_utilization, unified_7d_reset,
    unified_7d_sonnet_status, unified_7d_sonnet_utilization, unified_7d_sonnet_reset,
    org_id, updated_at, unified_reset
FROM "OAuthTokenRateLimitState"
WHERE token_key = $1
`

func (q *Queries) GetOAuthTokenRateLimitState(ctx context.Context, tokenKey string) (OAuthTokenRateLimitState, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenRateLimitState, tokenKey)
	var i OAuthTokenRateLimitState
	err := row.Scan(
		&i.TokenKey,
		&i.UnifiedStatus,
		&i.Unified5hStatus,
		&i.Unified5hUtilization,
		&i.Unified5hReset,
		&i.Unified7dStatus,
		&i.Unified7dUtilization,
		&i.Unified7dReset,
		&i.Unified7dSonnetStatus,
		&i.Unified7dSonnetUtilization,
		&i.Unified7dSonnetReset,
		&i.OrgID,
		&i.UpdatedAt,
		&i.UnifiedReset,
	)
	return i, err
}

const upsertOAuthTokenRateLimitState = `-- name: UpsertOAuthTokenRateLimitState :exec
INSERT INTO "OAuthTokenRateLimitState" (
    token_key, unified_status,
    unified_5h_status, unified_5h_utilization, unified_5h_reset,
    unified_7d_status, unified_7d_utilization, unified_7d_reset,
    unified_7d_sonnet_status, unified_7d_sonnet_utilization, unified_7d_sonnet_reset,
    org_id, unified_reset, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now())
ON CONFLICT (token_key) DO UPDATE SET
    unified_status = EXCLUDED.unified_status,
    unified_5h_status = EXCLUDED.unified_5h_status,
    unified_5h_utilization = EXCLUDED.unified_5h_utilization,
    unified_5h_reset = EXCLUDED.unified_5h_reset,
    unified_7d_status = EXCLUDED.unified_7d_status,
    unified_7d_utilization = EXCLUDED.unified_7d_utilization,
    unified_7d_reset = EXCLUDED.unified_7d_reset,
    unified_7d_sonnet_status = EXCLUDED.unified_7d_sonnet_status,
    unified_7d_sonnet_utilization = EXCLUDED.unified_7d_sonnet_utilization,
    unified_7d_sonnet_reset = EXCLUDED.unified_7d_sonnet_reset,
    org_id = EXCLUDED.org_id,
    unified_reset = EXCLUDED.unified_reset,
    updated_at = now()
`

type UpsertOAuthTokenRateLimitStateParams struct {
	TokenKey                   string  `json:"token_key"`
	UnifiedStatus              string  `json:"unified_status"`
	Unified5hStatus            string  `json:"unified_5h_status"`
	Unified5hUtilization       float64 `json:"unified_5h_utilization"`
	Unified5hReset             string  `json:"unified_5h_reset"`
	Unified7dStatus            string  `json:"unified_7d_status"`
	Unified7dUtilization       float64 `json:"unified_7d_utilization"`
	Unified7dReset             string  `json:"unified_7d_reset"`
	Unified7dSonnetStatus      string  `json:"unified_7d_sonnet_status"`
	Unified7dSonnetUtilization float64 `json:"unified_7d_sonnet_utilization"`
	Unified7dSonnetReset       string  `json:"unified_7d_sonnet_reset"`
	OrgID                      string  `json:"org_id"`
	UnifiedReset               string  `json:"unified_reset"`
}

func (q *Queries) UpsertOAuthTokenRateLimitState(ctx context.Context, arg UpsertOAuthTokenRateLimitStateParams) error {
	_, err := q.db.Exec(ctx, upsertOAuthTokenRateLimitState,
		arg.TokenKey,
		arg.UnifiedStatus,
		arg.Unified5hStatus,
		arg.Unified5hUtilization,
		arg.Unified5hReset,
		arg.Unified7dStatus,
		arg.Unified7dUtilization,
		arg.Unified7dReset,
		arg.Unified7dSonnetStatus,
		arg.Unified7dSonnetUtilization,
		arg.Unified7dSonnetReset,
		arg.OrgID,
		arg.UnifiedReset,
	)
	return err
}
