// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_token_metadata.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableOAuthToken = `-- name: DisableOAuthToken :exec
INSERT INTO "OAuthTokenMetadata" (token_key, org_id, disabled, updated_at)
VALUES ($1, '', true, now())
ON CONFLICT (token_key) DO UPDATE SET disabled = true, updated_at = now()
`

func (q *Queries) DisableOAuthToken(ctx context.Context, tokenKey string) error {
	_, err := q.db.Exec(ctx, disableOAuthToken, tokenKey)
	return err
}

const enableOAuthToken = `-- name: EnableOAuthToken :exec
INSERT INTO "OAuthTokenMetadata" (token_key, org_id, disabled, updated_at)
VALUES ($1, '', false, now())
ON CONFLICT (token_key) DO UPDATE SET disabled = false, updated_at = now()
`

func (q *Queries) EnableOAuthToken(ctx context.Context, tokenKey string) error {
	_, err := q.db.Exec(ctx, enableOAuthToken, tokenKey)
	return err
}

const getAllOAuthTokenMetadata = `-- name: GetAllOAuthTokenMetadata :many
SELECT token_key, org_id, disabled, updated_at
FROM "OAuthTokenMetadata"
`

type GetAllOAuthTokenMetadataRow struct {
	TokenKey  string             `json:"token_key"`
	OrgID     string             `json:"org_id"`
	Disabled  bool               `json:"disabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAllOAuthTokenMetadata(ctx context.Context) ([]GetAllOAuthTokenMetadataRow, error) {
	rows, err := q.db.Query(ctx, getAllOAuthTokenMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOAuthTokenMetadataRow
	for rows.Next() {
		var i GetAllOAuthTokenMetadataRow
		if err := rows.Scan(
			&i.TokenKey,
			&i.OrgID,
			&i.Disabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthTokenMetadata = `-- name: GetOAuthTokenMetadata :one
SELECT token_key, org_id, disabled, updated_at
FROM "OAuthTokenMetadata"
WHERE token_key = $1
`

type GetOAuthTokenMetadataRow struct {
	TokenKey  string             `json:"token_key"`
	OrgID     string             `json:"org_id"`
	Disabled  bool               `json:"disabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOAuthTokenMetadata(ctx context.Context, tokenKey string) (GetOAuthTokenMetadataRow, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenMetadata, tokenKey)
	var i GetOAuthTokenMetadataRow
	err := row.Scan(
		&i.TokenKey,
		&i.OrgID,
		&i.Disabled,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthTokenMetadata = `-- name: UpsertOAuthTokenMetadata :exec
INSERT INTO "OAuthTokenMetadata" (token_key, org_id, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (token_key) DO UPDATE SET
    org_id = EXCLUDED.org_id,
    updated_at = now()
`

type UpsertOAuthTokenMetadataParams struct {
	TokenKey string `json:"token_key"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) UpsertOAuthTokenMetadata(ctx context.Context, arg UpsertOAuthTokenMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertOAuthTokenMetadata, arg.TokenKey, arg.OrgID)
	return err
}
