// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_membership.sql

package db

import (
	"context"
)

const addOrgMember = `-- name: AddOrgMember :one
INSERT INTO "OrganizationMembership" (user_id, organization_id, user_role, budget_id)
VALUES ($1, $2, $3, $4)
RETURNING user_id, organization_id, user_role, spend, budget_id, created_at, updated_at
`

type AddOrgMemberParams struct {
	UserID         string  `json:"user_id"`
	OrganizationID string  `json:"organization_id"`
	UserRole       *string `json:"user_role"`
	BudgetID       *string `json:"budget_id"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, addOrgMember,
		arg.UserID,
		arg.OrganizationID,
		arg.UserRole,
		arg.BudgetID,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.UserRole,
		&i.Spend,
		&i.BudgetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgMember = `-- name: DeleteOrgMember :exec
DELETE FROM "OrganizationMembership"
WHERE user_id = $1 AND organization_id = $2
`

type DeleteOrgMemberParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrgMember, arg.UserID, arg.OrganizationID)
	return err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT user_id, organization_id, user_role, spend, budget_id, created_at, updated_at FROM "OrganizationMembership"
WHERE user_id = $1 AND organization_id = $2
`

type GetOrgMemberParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.UserID, arg.OrganizationID)
	var i OrganizationMembership
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.UserRole,
		&i.Spend,
		&i.BudgetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT user_id, organization_id, user_role, spend, budget_id, created_at, updated_at FROM "OrganizationMembership"
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrgMembers(ctx context.Context, organizationID string) ([]OrganizationMembership, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMembership
	for rows.Next() {
		var i OrganizationMembership
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.UserRole,
			&i.Spend,
			&i.BudgetID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgMember = `-- name: UpdateOrgMember :one
UPDATE "OrganizationMembership"
SET user_role = COALESCE($3, user_role),
    budget_id = COALESCE($4, budget_id),
    updated_at = NOW()
WHERE user_id = $1 AND organization_id = $2
RETURNING user_id, organization_id, user_role, spend, budget_id, created_at, updated_at
`

type UpdateOrgMemberParams struct {
	UserID         string  `json:"user_id"`
	OrganizationID string  `json:"organization_id"`
	UserRole       *string `json:"user_role"`
	BudgetID       *string `json:"budget_id"`
}

func (q *Queries) UpdateOrgMember(ctx context.Context, arg UpdateOrgMemberParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateOrgMember,
		arg.UserID,
		arg.OrganizationID,
		arg.UserRole,
		arg.BudgetID,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.UserRole,
		&i.Spend,
		&i.BudgetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
