// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package db

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO "OrganizationTable" (organization_id, organization_alias, max_budget, models, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING organization_id, organization_alias, budget_id, metadata, models, spend, max_budget, tpm_limit, rpm_limit, budget_duration, budget_reset_at, created_at, created_by, updated_at, updated_by
`

type CreateOrganizationParams struct {
	OrganizationID    string   `json:"organization_id"`
	OrganizationAlias *string  `json:"organization_alias"`
	MaxBudget         *float64 `json:"max_budget"`
	Models            []string `json:"models"`
	CreatedBy         string   `json:"created_by"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (OrganizationTable, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.OrganizationID,
		arg.OrganizationAlias,
		arg.MaxBudget,
		arg.Models,
		arg.CreatedBy,
	)
	var i OrganizationTable
	err := row.Scan(
		&i.OrganizationID,
		&i.OrganizationAlias,
		&i.BudgetID,
		&i.Metadata,
		&i.Models,
		&i.Spend,
		&i.MaxBudget,
		&i.TpmLimit,
		&i.RpmLimit,
		&i.BudgetDuration,
		&i.BudgetResetAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM "OrganizationTable" WHERE organization_id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, deleteOrganization, organizationID)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT organization_id, organization_alias, budget_id, metadata, models, spend, max_budget, tpm_limit, rpm_limit, budget_duration, budget_reset_at, created_at, created_by, updated_at, updated_by FROM "OrganizationTable" WHERE organization_id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, organizationID string) (OrganizationTable, error) {
	row := q.db.QueryRow(ctx, getOrganization, organizationID)
	var i OrganizationTable
	err := row.Scan(
		&i.OrganizationID,
		&i.OrganizationAlias,
		&i.BudgetID,
		&i.Metadata,
		&i.Models,
		&i.Spend,
		&i.MaxBudget,
		&i.TpmLimit,
		&i.RpmLimit,
		&i.BudgetDuration,
		&i.BudgetResetAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT organization_id, organization_alias, budget_id, metadata, models, spend, max_budget, tpm_limit, rpm_limit, budget_duration, budget_reset_at, created_at, created_by, updated_at, updated_by FROM "OrganizationTable" ORDER BY created_at DESC
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]OrganizationTable, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationTable
	for rows.Next() {
		var i OrganizationTable
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationAlias,
			&i.BudgetID,
			&i.Metadata,
			&i.Models,
			&i.Spend,
			&i.MaxBudget,
			&i.TpmLimit,
			&i.RpmLimit,
			&i.BudgetDuration,
			&i.BudgetResetAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE "OrganizationTable"
SET organization_alias = COALESCE($2, organization_alias),
    max_budget = COALESCE($3, max_budget),
    updated_at = NOW()
WHERE organization_id = $1
RETURNING organization_id, organization_alias, budget_id, metadata, models, spend, max_budget, tpm_limit, rpm_limit, budget_duration, budget_reset_at, created_at, created_by, updated_at, updated_by
`

type UpdateOrganizationParams struct {
	OrganizationID    string   `json:"organization_id"`
	OrganizationAlias *string  `json:"organization_alias"`
	MaxBudget         *float64 `json:"max_budget"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (OrganizationTable, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.OrganizationID, arg.OrganizationAlias, arg.MaxBudget)
	var i OrganizationTable
	err := row.Scan(
		&i.OrganizationID,
		&i.OrganizationAlias,
		&i.BudgetID,
		&i.Metadata,
		&i.Models,
		&i.Spend,
		&i.MaxBudget,
		&i.TpmLimit,
		&i.RpmLimit,
		&i.BudgetDuration,
		&i.BudgetResetAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
