// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO "PolicyTable" (name, parent_id, conditions, guardrails_add, guardrails_remove, pipeline, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, parent_id, conditions, guardrails_add, guardrails_remove, pipeline, description, created_by, created_at, updated_at
`

type CreatePolicyParams struct {
	Name             string   `json:"name"`
	ParentID         *string  `json:"parent_id"`
	Conditions       []byte   `json:"conditions"`
	GuardrailsAdd    []string `json:"guardrails_add"`
	GuardrailsRemove []string `json:"guardrails_remove"`
	Pipeline         []byte   `json:"pipeline"`
	Description      *string  `json:"description"`
	CreatedBy        *string  `json:"created_by"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (PolicyTable, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.Name,
		arg.ParentID,
		arg.Conditions,
		arg.GuardrailsAdd,
		arg.GuardrailsRemove,
		arg.Pipeline,
		arg.Description,
		arg.CreatedBy,
	)
	var i PolicyTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Conditions,
		&i.GuardrailsAdd,
		&i.GuardrailsRemove,
		&i.Pipeline,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPolicyAttachment = `-- name: CreatePolicyAttachment :one
INSERT INTO "PolicyAttachmentTable" (policy_name, scope, teams, keys, models, tags, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, policy_name, scope, teams, keys, models, tags, created_by, created_at, updated_at
`

type CreatePolicyAttachmentParams struct {
	PolicyName string   `json:"policy_name"`
	Scope      *string  `json:"scope"`
	Teams      []string `json:"teams"`
	Keys       []string `json:"keys"`
	Models     []string `json:"models"`
	Tags       []string `json:"tags"`
	CreatedBy  *string  `json:"created_by"`
}

func (q *Queries) CreatePolicyAttachment(ctx context.Context, arg CreatePolicyAttachmentParams) (PolicyAttachmentTable, error) {
	row := q.db.QueryRow(ctx, createPolicyAttachment,
		arg.PolicyName,
		arg.Scope,
		arg.Teams,
		arg.Keys,
		arg.Models,
		arg.Tags,
		arg.CreatedBy,
	)
	var i PolicyAttachmentTable
	err := row.Scan(
		&i.ID,
		&i.PolicyName,
		&i.Scope,
		&i.Teams,
		&i.Keys,
		&i.Models,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM "PolicyTable" WHERE id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePolicy, id)
	return err
}

const deletePolicyAttachment = `-- name: DeletePolicyAttachment :exec
DELETE FROM "PolicyAttachmentTable" WHERE id = $1
`

func (q *Queries) DeletePolicyAttachment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePolicyAttachment, id)
	return err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, name, parent_id, conditions, guardrails_add, guardrails_remove, pipeline, description, created_by, created_at, updated_at FROM "PolicyTable" WHERE id = $1
`

func (q *Queries) GetPolicy(ctx context.Context, id string) (PolicyTable, error) {
	row := q.db.QueryRow(ctx, getPolicy, id)
	var i PolicyTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Conditions,
		&i.GuardrailsAdd,
		&i.GuardrailsRemove,
		&i.Pipeline,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyAttachment = `-- name: GetPolicyAttachment :one
SELECT id, policy_name, scope, teams, keys, models, tags, created_by, created_at, updated_at FROM "PolicyAttachmentTable" WHERE id = $1
`

func (q *Queries) GetPolicyAttachment(ctx context.Context, id string) (PolicyAttachmentTable, error) {
	row := q.db.QueryRow(ctx, getPolicyAttachment, id)
	var i PolicyAttachmentTable
	err := row.Scan(
		&i.ID,
		&i.PolicyName,
		&i.Scope,
		&i.Teams,
		&i.Keys,
		&i.Models,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyByName = `-- name: GetPolicyByName :one
SELECT id, name, parent_id, conditions, guardrails_add, guardrails_remove, pipeline, description, created_by, created_at, updated_at FROM "PolicyTable" WHERE name = $1
`

func (q *Queries) GetPolicyByName(ctx context.Context, name string) (PolicyTable, error) {
	row := q.db.QueryRow(ctx, getPolicyByName, name)
	var i PolicyTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Conditions,
		&i.GuardrailsAdd,
		&i.GuardrailsRemove,
		&i.Pipeline,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyChain = `-- name: GetPolicyChain :many
WITH RECURSIVE chain AS (
    SELECT pt.id, pt.name, pt.parent_id, pt.conditions, pt.guardrails_add, pt.guardrails_remove, pt.pipeline, pt.description, pt.created_by, pt.created_at, pt.updated_at, 1 AS depth FROM "PolicyTable" pt WHERE pt.name = $1
    UNION ALL
    SELECT p.id, p.name, p.parent_id, p.conditions, p.guardrails_add, p.guardrails_remove, p.pipeline, p.description, p.created_by, p.created_at, p.updated_at, c.depth + 1 FROM "PolicyTable" p
    JOIN chain c ON p.id = c.parent_id
    WHERE c.depth < 50
)
SELECT id, name, parent_id, conditions, guardrails_add, guardrails_remove, pipeline, description, created_by, created_at, updated_at FROM chain
`

type GetPolicyChainRow struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	ParentID         *string            `json:"parent_id"`
	Conditions       []byte             `json:"conditions"`
	GuardrailsAdd    []string           `json:"guardrails_add"`
	GuardrailsRemove []string           `json:"guardrails_remove"`
	Pipeline         []byte             `json:"pipeline"`
	Description      *string            `json:"description"`
	CreatedBy        *string            `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPolicyChain(ctx context.Context, name string) ([]GetPolicyChainRow, error) {
	rows, err := q.db.Query(ctx, getPolicyChain, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPolicyChainRow
	for rows.Next() {
		var i GetPolicyChainRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Conditions,
			&i.GuardrailsAdd,
			&i.GuardrailsRemove,
			&i.Pipeline,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, parent_id, conditions, guardrails_add, guardrails_remove, pipeline, description, created_by, created_at, updated_at FROM "PolicyTable" ORDER BY created_at DESC
`

func (q *Queries) ListPolicies(ctx context.Context) ([]PolicyTable, error) {
	rows, err := q.db.Query(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyTable
	for rows.Next() {
		var i PolicyTable
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Conditions,
			&i.GuardrailsAdd,
			&i.GuardrailsRemove,
			&i.Pipeline,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyAttachments = `-- name: ListPolicyAttachments :many
SELECT id, policy_name, scope, teams, keys, models, tags, created_by, created_at, updated_at FROM "PolicyAttachmentTable" ORDER BY created_at DESC
`

func (q *Queries) ListPolicyAttachments(ctx context.Context) ([]PolicyAttachmentTable, error) {
	rows, err := q.db.Query(ctx, listPolicyAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyAttachmentTable
	for rows.Next() {
		var i PolicyAttachmentTable
		if err := rows.Scan(
			&i.ID,
			&i.PolicyName,
			&i.Scope,
			&i.Teams,
			&i.Keys,
			&i.Models,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyAttachmentsByPolicy = `-- name: ListPolicyAttachmentsByPolicy :many
SELECT id, policy_name, scope, teams, keys, models, tags, created_by, created_at, updated_at FROM "PolicyAttachmentTable" WHERE policy_name = $1
`

func (q *Queries) ListPolicyAttachmentsByPolicy(ctx context.Context, policyName string) ([]PolicyAttachmentTable, error) {
	rows, err := q.db.Query(ctx, listPolicyAttachmentsByPolicy, policyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyAttachmentTable
	for rows.Next() {
		var i PolicyAttachmentTable
		if err := rows.Scan(
			&i.ID,
			&i.PolicyName,
			&i.Scope,
			&i.Teams,
			&i.Keys,
			&i.Models,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE "PolicyTable"
SET name = COALESCE($2, name),
    parent_id = $3,
    conditions = COALESCE($4, conditions),
    guardrails_add = COALESCE($5, guardrails_add),
    guardrails_remove = COALESCE($6, guardrails_remove),
    pipeline = $7,
    description = COALESCE($8, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, parent_id, conditions, guardrails_add, guardrails_remove, pipeline, description, created_by, created_at, updated_at
`

type UpdatePolicyParams struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	ParentID         *string  `json:"parent_id"`
	Conditions       []byte   `json:"conditions"`
	GuardrailsAdd    []string `json:"guardrails_add"`
	GuardrailsRemove []string `json:"guardrails_remove"`
	Pipeline         []byte   `json:"pipeline"`
	Description      *string  `json:"description"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (PolicyTable, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Conditions,
		arg.GuardrailsAdd,
		arg.GuardrailsRemove,
		arg.Pipeline,
		arg.Description,
	)
	var i PolicyTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Conditions,
		&i.GuardrailsAdd,
		&i.GuardrailsRemove,
		&i.Pipeline,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
