// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proxy_model.sql

package db

import (
	"context"
)

const countProxyModels = `-- name: CountProxyModels :one
SELECT COUNT(*) FROM "ProxyModelTable"
WHERE
    ($1::text IS NULL
     OR model_name ILIKE '%' || $1::text || '%'
     OR model_id ILIKE '%' || $1::text || '%'
     OR tianji_params->>'model' ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountProxyModels(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countProxyModels, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProxyModel = `-- name: CreateProxyModel :one
INSERT INTO "ProxyModelTable" (
    model_id, model_name, tianji_params, model_info, created_by
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING model_id, model_name, tianji_params, model_info, created_at, created_by, updated_at, updated_by
`

type CreateProxyModelParams struct {
	ModelID      string `json:"model_id"`
	ModelName    string `json:"model_name"`
	TianjiParams []byte `json:"tianji_params"`
	ModelInfo    []byte `json:"model_info"`
	CreatedBy    string `json:"created_by"`
}

func (q *Queries) CreateProxyModel(ctx context.Context, arg CreateProxyModelParams) (ProxyModelTable, error) {
	row := q.db.QueryRow(ctx, createProxyModel,
		arg.ModelID,
		arg.ModelName,
		arg.TianjiParams,
		arg.ModelInfo,
		arg.CreatedBy,
	)
	var i ProxyModelTable
	err := row.Scan(
		&i.ModelID,
		&i.ModelName,
		&i.TianjiParams,
		&i.ModelInfo,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteProxyModel = `-- name: DeleteProxyModel :exec
DELETE FROM "ProxyModelTable"
WHERE model_id = $1
`

func (q *Queries) DeleteProxyModel(ctx context.Context, modelID string) error {
	_, err := q.db.Exec(ctx, deleteProxyModel, modelID)
	return err
}

const getProxyModel = `-- name: GetProxyModel :one
SELECT model_id, model_name, tianji_params, model_info, created_at, created_by, updated_at, updated_by FROM "ProxyModelTable"
WHERE model_id = $1
`

func (q *Queries) GetProxyModel(ctx context.Context, modelID string) (ProxyModelTable, error) {
	row := q.db.QueryRow(ctx, getProxyModel, modelID)
	var i ProxyModelTable
	err := row.Scan(
		&i.ModelID,
		&i.ModelName,
		&i.TianjiParams,
		&i.ModelInfo,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getProxyModelByName = `-- name: GetProxyModelByName :one
SELECT model_id, model_name, tianji_params, model_info, created_at, created_by, updated_at, updated_by FROM "ProxyModelTable"
WHERE model_name = $1
`

func (q *Queries) GetProxyModelByName(ctx context.Context, modelName string) (ProxyModelTable, error) {
	row := q.db.QueryRow(ctx, getProxyModelByName, modelName)
	var i ProxyModelTable
	err := row.Scan(
		&i.ModelID,
		&i.ModelName,
		&i.TianjiParams,
		&i.ModelInfo,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listProxyModels = `-- name: ListProxyModels :many
SELECT model_id, model_name, tianji_params, model_info, created_at, created_by, updated_at, updated_by FROM "ProxyModelTable"
ORDER BY created_at DESC
`

func (q *Queries) ListProxyModels(ctx context.Context) ([]ProxyModelTable, error) {
	rows, err := q.db.Query(ctx, listProxyModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyModelTable
	for rows.Next() {
		var i ProxyModelTable
		if err := rows.Scan(
			&i.ModelID,
			&i.ModelName,
			&i.TianjiParams,
			&i.ModelInfo,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyModelsPage = `-- name: ListProxyModelsPage :many
SELECT model_id, model_name, tianji_params, model_info, created_at, created_by, updated_at, updated_by FROM "ProxyModelTable"
WHERE
    ($1::text IS NULL
     OR model_name ILIKE '%' || $1::text || '%'
     OR model_id ILIKE '%' || $1::text || '%'
     OR tianji_params->>'model' ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListProxyModelsPageParams struct {
	Search     *string `json:"search"`
	PageOffset int32   `json:"page_offset"`
	PageLimit  int32   `json:"page_limit"`
}

func (q *Queries) ListProxyModelsPage(ctx context.Context, arg ListProxyModelsPageParams) ([]ProxyModelTable, error) {
	rows, err := q.db.Query(ctx, listProxyModelsPage, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyModelTable
	for rows.Next() {
		var i ProxyModelTable
		if err := rows.Scan(
			&i.ModelID,
			&i.ModelName,
			&i.TianjiParams,
			&i.ModelInfo,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProxyModel = `-- name: UpdateProxyModel :one
UPDATE "ProxyModelTable"
SET
    model_name = COALESCE($2, model_name),
    tianji_params = COALESCE($3, tianji_params),
    model_info = COALESCE($4, model_info),
    updated_at = NOW(),
    updated_by = $5
WHERE model_id = $1
RETURNING model_id, model_name, tianji_params, model_info, created_at, created_by, updated_at, updated_by
`

type UpdateProxyModelParams struct {
	ModelID      string `json:"model_id"`
	ModelName    string `json:"model_name"`
	TianjiParams []byte `json:"tianji_params"`
	ModelInfo    []byte `json:"model_info"`
	UpdatedBy    string `json:"updated_by"`
}

func (q *Queries) UpdateProxyModel(ctx context.Context, arg UpdateProxyModelParams) (ProxyModelTable, error) {
	row := q.db.QueryRow(ctx, updateProxyModel,
		arg.ModelID,
		arg.ModelName,
		arg.TianjiParams,
		arg.ModelInfo,
		arg.UpdatedBy,
	)
	var i ProxyModelTable
	err := row.Scan(
		&i.ModelID,
		&i.ModelName,
		&i.TianjiParams,
		&i.ModelInfo,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
