// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skill.sql

package db

import (
	"context"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO "SkillsTable" (
    display_title, description, instructions, source,
    latest_version, file_content, file_name, file_type,
    metadata, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING skill_id, display_title, description, instructions, source, latest_version, file_content, file_name, file_type, metadata, created_at, created_by, updated_at, updated_by
`

type CreateSkillParams struct {
	DisplayTitle  string `json:"display_title"`
	Description   string `json:"description"`
	Instructions  string `json:"instructions"`
	Source        string `json:"source"`
	LatestVersion string `json:"latest_version"`
	FileContent   []byte `json:"file_content"`
	FileName      string `json:"file_name"`
	FileType      string `json:"file_type"`
	Metadata      []byte `json:"metadata"`
	CreatedBy     string `json:"created_by"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (SkillsTable, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.DisplayTitle,
		arg.Description,
		arg.Instructions,
		arg.Source,
		arg.LatestVersion,
		arg.FileContent,
		arg.FileName,
		arg.FileType,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i SkillsTable
	err := row.Scan(
		&i.SkillID,
		&i.DisplayTitle,
		&i.Description,
		&i.Instructions,
		&i.Source,
		&i.LatestVersion,
		&i.FileContent,
		&i.FileName,
		&i.FileType,
		&i.Metadata,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM "SkillsTable"
WHERE skill_id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, skillID string) error {
	_, err := q.db.Exec(ctx, deleteSkill, skillID)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT skill_id, display_title, description, instructions, source, latest_version, file_content, file_name, file_type, metadata, created_at, created_by, updated_at, updated_by FROM "SkillsTable"
WHERE skill_id = $1
`

func (q *Queries) GetSkill(ctx context.Context, skillID string) (SkillsTable, error) {
	row := q.db.QueryRow(ctx, getSkill, skillID)
	var i SkillsTable
	err := row.Scan(
		&i.SkillID,
		&i.DisplayTitle,
		&i.Description,
		&i.Instructions,
		&i.Source,
		&i.LatestVersion,
		&i.FileContent,
		&i.FileName,
		&i.FileType,
		&i.Metadata,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT skill_id, display_title, description, instructions, source, latest_version, file_content, file_name, file_type, metadata, created_at, created_by, updated_at, updated_by FROM "SkillsTable"
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSkillsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSkills(ctx context.Context, arg ListSkillsParams) ([]SkillsTable, error) {
	rows, err := q.db.Query(ctx, listSkills, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillsTable
	for rows.Next() {
		var i SkillsTable
		if err := rows.Scan(
			&i.SkillID,
			&i.DisplayTitle,
			&i.Description,
			&i.Instructions,
			&i.Source,
			&i.LatestVersion,
			&i.FileContent,
			&i.FileName,
			&i.FileType,
			&i.Metadata,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
