// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag_mgmt.sql

package db

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO "TagTable" (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at
`

type CreateTagParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (TagTable, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Description)
	var i TagTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM "TagTable" WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, description, created_at FROM "TagTable" WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id string) (TagTable, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i TagTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, description, created_at FROM "TagTable" WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (TagTable, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i TagTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, description, created_at FROM "TagTable" ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]TagTable, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagTable
	for rows.Next() {
		var i TagTable
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE "TagTable"
SET name = COALESCE($2, name),
    description = COALESCE($3, description)
WHERE id = $1
RETURNING id, name, description, created_at
`

type UpdateTagParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (TagTable, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Description)
	var i TagTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
